#-------------------------------
# General Site Settings

menu:
# - {name: 'Projects', url: ''}
- {name: 'Politicas', url: 'pages/politicas.html'}
# - {name: 'Sobre', url: 'pages/about.html'}
- {name: 'Equipe', url: 'pages/equipe.html'}

#-------------------------------
